---
AWSTemplateFormatVersion: "2010-09-09"
Description: Lambda function with dynamodb table.
Resources:
  # DynamoDB Table
  DynamoDBTable:
    Type: "AWS::DynamoDB::Table"
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      AttributeDefinitions:
        - AttributeName: partition
          AttributeType: S
      KeySchema:
        - AttributeName: partition
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  # IAM Roles
  WebServiceLambdaExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AWSLambdaExecute"
      Policies:
        - PolicyName: "dynamodb-access"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "dynamodb:Query"
                  - "dynamodb:Scan"
                  - "dynamodb:GetItem"
                  - "dynamodb:PutItem"
                  - "dynamodb:UpdateItem"
                  - "dynamodb:DeleteItem"
                Resource: !GetAtt ["DynamoDBTable", "Arn"]
  # Lambda Functions
  WebServiceLambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Code: ./dist/web_service
      Handler: "function.handler"
      Role: !GetAtt ["WebServiceLambdaExecutionRole", "Arn"]
      Runtime: "provided.al2"
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref "DynamoDBTable"
          PROTOCOL: "https"
  WebServiceLambdaFunctionLogGroup:
    Type: "AWS::Logs::LogGroup"
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      LogGroupName: !Sub
        - '/aws/lambda/${FunctionName}'
        - FunctionName: !Ref "WebServiceLambdaFunction"
      RetentionInDays: 3
