name: Deploy

on:
  push:
    branches: ["deploy"]

env:
  AWS_REGION: eu-central-1 # set this to your preferred AWS region, e.g. us-west-1
  CARGO_TERM_COLOR: always
  S3_BUCKET: cf-templates-jbywbbl8iz9d-eu-central-1 # needs to be in the same AWS region as the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Package
        run: |
          docker-compose -f docker/build/docker-compose.yml up \
                         --exit-code-from amazonlinux2
          mkdir -p dist/web_service
          cp target/release/web_service dist/web_service/bootstrap
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Upload
        run: |
          aws cloudformation package \
            --template-file cloudformation.yml \
            --s3-bucket "$S3_BUCKET" \
            --output-template-file packaged.yml
      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: rust-lambda
          template: packaged.yml